{-# LANGUAGE OverloadedStrings #-}

-- | Pure Gentoo Dockerfile render for the materialize image.
module Update.Materialize.Recipe
  ( RecipeArch (..),
    lookupRecipeArch,
    renderMaterializeDockerfile,
  )
where

import Data.List (sortOn)
import Data.Text (Text)
import Data.Text qualified as T
import Update.Materialize.Resolve
  ( ResolvedInstall (..),
    ResolvedToolchain (..),
    ToolchainKind (..),
  )

-- | Host map result: Portage KEYWORDS token plus official OpenRC Hub tag.
data RecipeArch = RecipeArch
  { raKeywords :: Text,
    raHubTag :: Text
  }
  deriving (Eq, Show)

-- | Closed @uname -m@ → (KEYWORDS, OpenRC Hub tag). Unknown machine is a miss.
lookupRecipeArch :: String -> Maybe RecipeArch
lookupRecipeArch machine = case machine of
  "x86_64" -> Just amd64
  "amd64" -> Just amd64
  "aarch64" -> Just arm64
  "arm64" -> Just arm64
  "ppc64le" -> Just (RecipeArch "ppc64" "ppc64le-openrc")
  "riscv64" -> Just (RecipeArch "riscv" "rv64_lp64d-openrc")
  "s390x" -> Just (RecipeArch "s390" "s390x-openrc")
  "i686" -> Just x86
  "i386" -> Just x86
  "armv7l" -> Just (RecipeArch "arm" "armv7a_hardfp-openrc")
  "armv6l" -> Just (RecipeArch "arm" "armv6j_hardfp-openrc")
  _ -> Nothing
  where
    amd64 = RecipeArch "amd64" "amd64-openrc"
    arm64 = RecipeArch "arm64" "arm64-openrc"
    x86 = RecipeArch "x86" "i686-openrc"

distfilesCacheId :: Text
distfilesCacheId = "mndz-materialize-distfiles"

binpkgsCacheId :: Text
binpkgsCacheId = "mndz-materialize-binpkgs"

-- | Render a BuildKit Dockerfile from already-resolved toolchain installs.
--
-- Overlay is bind-mounted at the host path (read-only) via an extra build
-- context named @overlay@; distfiles/binpkgs use stable-id cache mounts. Bun is
-- @dev-lang/bun-bin::mndz@ only. Qlot is overlay @dev-lisp/qlot::mndz@ after
-- @ENV SBCL_HOME@. No official go.dev / nodejs.org / GitHub zip toolchain
-- URLs. @FROM@ uses the OpenRC Hub tag. Layer order is rust → sbcl → qlot →
-- node → go → bun.
renderMaterializeDockerfile ::
  RecipeArch ->
  -- | Host overlay path (bind destination and repos.conf location).
  FilePath ->
  [ResolvedInstall] ->
  Text
renderMaterializeDockerfile arch overlayPath installs =
  T.unlines $
    header
      <> [runCache baseCmds]
      <> concatMap (installRuns overlay (raKeywords arch)) ordered
      <> builderHome
  where
    overlay = T.pack overlayPath
    ordered = sortOn (kindRank . riKind) installs
    header =
      [ "# syntax=docker/dockerfile:1",
        "# Generated by mndz-overlay-manager. Do not edit.",
        "",
        "FROM gentoo/stage3:" <> raHubTag arch,
        "",
        "ENV FEATURES=\"getbinpkg buildpkg -news -ipc-sandbox -network-sandbox -pid-sandbox\"",
        "ENV EMERGE_DEFAULT_OPTS=\"--quiet-build=y --with-bdeps=n --usepkg\"",
        ""
      ]
    baseCmds =
      [ "emerge-webrsync",
        "(command -v getuto >/dev/null && getuto || true)",
        "emerge --oneshot sys-apps/portage",
        "emerge -n app-arch/tar app-arch/xz-utils app-misc/ca-certificates app-arch/unzip dev-vcs/git net-misc/aria2 net-misc/wget"
      ]
    builderHome =
      [ "RUN mkdir -p /home/builder/.config /tmp/builder-cache \\",
        " && chmod 0777 /home/builder /home/builder/.config /tmp/builder-cache",
        "",
        "ENV HOME=/home/builder",
        "WORKDIR /home/builder",
        ""
      ]

kindRank :: ToolchainKind -> Int
kindRank = \case
  TkRust -> 0
  TkSbcl -> 1
  TkQlot -> 2
  TkNode -> 3
  TkGo -> 4
  TkBun -> 5

-- | Gentoo @get_libdir@ for mapped KEYWORDS tokens.
gentooLibdir :: Text -> Text
gentooLibdir kw
  | kw `elem` ["amd64", "arm64", "ppc64", "riscv", "s390"] = "lib64"
  | otherwise = "lib"

installRuns :: Text -> Text -> ResolvedInstall -> [Text]
installRuns overlay keywords (ResolvedInstall kind rt) = case kind of
  TkRust ->
    [ runCache (portageCmds rt kind ["emerge -n app-portage/pycargoebuild"]),
      ""
    ]
  TkSbcl ->
    let libdir = gentooLibdir keywords
     in [ runCache (portageCmds rt kind []),
          "",
          "ENV SBCL_HOME=/usr/" <> libdir <> "/sbcl",
          "ENV SBCL_SOURCE_ROOT=/usr/" <> libdir <> "/sbcl/src",
          ""
        ]
  TkQlot ->
    [runCacheOverlay overlay (overlayBindCmds overlay rt kind), ""]
  TkNode ->
    [runCache (portageCmds rt kind []), ""]
  TkGo ->
    [runCache (portageCmds rt kind []), ""]
  TkBun ->
    [runCacheOverlay overlay (overlayBindCmds overlay rt kind), ""]

portageCmds :: ResolvedToolchain -> ToolchainKind -> [Text] -> [Text]
portageCmds rt kind extra =
  ["emerge-webrsync"]
    <> acceptCmds kind rt
    <> [emergeCmd rt]
    <> extra

overlayBindCmds :: Text -> ResolvedToolchain -> ToolchainKind -> [Text]
overlayBindCmds overlay rt kind =
  [ "emerge-webrsync",
    "mkdir -p /etc/portage/repos.conf /etc/portage/package.accept_keywords",
    "printf '[mndz]\\nlocation = "
      <> overlay
      <> "\\nmaster = gentoo\\nauto-sync = no\\n' > /etc/portage/repos.conf/mndz.conf"
  ]
    <> overlayAcceptCmds kind rt
    <> [emergeCmd rt]

emergeCmd :: ResolvedToolchain -> Text
emergeCmd rt = "emerge -n \"" <> rtEmergeSpec rt <> "\""

acceptCmds :: ToolchainKind -> ResolvedToolchain -> [Text]
acceptCmds kind rt = case rtAcceptLine rt of
  Nothing -> []
  Just line ->
    [ "mkdir -p /etc/portage/package.accept_keywords",
      printfAccept kind line
    ]

-- | Overlay-bind RUN already created @package.accept_keywords@ next to repos.conf.
overlayAcceptCmds :: ToolchainKind -> ResolvedToolchain -> [Text]
overlayAcceptCmds kind rt = case rtAcceptLine rt of
  Nothing -> []
  Just line -> [printfAccept kind line]

printfAccept :: ToolchainKind -> Text -> Text
printfAccept kind line =
  "printf '"
    <> line
    <> "\\n' > /etc/portage/package.accept_keywords/mndz-"
    <> kindFile kind

kindFile :: ToolchainKind -> Text
kindFile = \case
  TkRust -> "rust"
  TkSbcl -> "sbcl"
  TkQlot -> "qlot"
  TkNode -> "node"
  TkGo -> "go"
  TkBun -> "bun"

runCache :: [Text] -> Text
runCache cmds =
  "RUN --mount=type=cache,id="
    <> distfilesCacheId
    <> ",target=/var/cache/distfiles \\\n\
       \    --mount=type=cache,id="
    <> binpkgsCacheId
    <> ",target=/var/cache/binpkgs \\\n\
       \    "
    <> T.intercalate " \\\n && " cmds

runCacheOverlay :: Text -> [Text] -> Text
runCacheOverlay overlay cmds =
  "RUN --mount=type=bind,from=overlay,source=/,target="
    <> overlay
    <> ",ro \\\n\
       \    --mount=type=cache,id="
    <> distfilesCacheId
    <> ",target=/var/cache/distfiles \\\n\
       \    --mount=type=cache,id="
    <> binpkgsCacheId
    <> ",target=/var/cache/binpkgs \\\n\
       \    "
    <> T.intercalate " \\\n && " cmds
