{-# LANGUAGE OverloadedStrings #-}

-- | Pure Gentoo Dockerfile render for the materialize image.
module Update.Materialize.Recipe
  ( RecipeArch (..),
    renderMaterializeDockerfile,
  )
where

import Data.Maybe (isJust)
import Data.Text (Text)
import Data.Text qualified as T
import Update.Materialize.Floors (NeededFloors (..))

-- | Gentoo arch token used for stage3 and package.accept_keywords.
newtype RecipeArch = RecipeArch {unRecipeArch :: Text}
  deriving (Eq, Show)

-- | Render a BuildKit Dockerfile for the needed floors.
--
-- Overlay is bind-mounted at the host path (read-only) via an extra build
-- context named @overlay@; distfiles/binpkgs use cache mounts. Bun is
-- @dev-lang/bun-bin::mndz@ only. No official go.dev / nodejs.org / GitHub zip
-- toolchain URLs.
renderMaterializeDockerfile ::
  NeededFloors ->
  RecipeArch ->
  -- | Host overlay path (bind destination and repos.conf location).
  FilePath ->
  Text
renderMaterializeDockerfile floors arch overlayPath =
  T.unlines $
    header
      <> [runCache baseCmds]
      <> rustRuns
      <> sbclRuns
      <> nodeRuns
      <> goRuns
      <> bunRuns
      <> builderHome
  where
    archTok = unRecipeArch arch
    overlay = T.pack overlayPath
    header =
      [ "# syntax=docker/dockerfile:1",
        "# Generated by mndz-overlay-manager. Do not edit.",
        "",
        "FROM gentoo/stage3:" <> archTok,
        "",
        "ENV FEATURES=\"getbinpkg -news -ipc-sandbox -network-sandbox -pid-sandbox\"",
        "ENV EMERGE_DEFAULT_OPTS=\"--quiet-build=y --with-bdeps=n\"",
        ""
      ]
    baseCmds =
      [ "emerge-webrsync",
        "(command -v getuto >/dev/null && getuto || true)",
        "emerge --oneshot sys-apps/portage",
        "emerge -n app-arch/tar app-arch/xz-utils app-misc/ca-certificates app-arch/unzip dev-vcs/git net-misc/aria2 net-misc/wget"
      ]
    rustRuns
      | isJust (nfRust floors) =
          [ runCache
              [ "emerge-webrsync",
                emergeBinThenSrc "dev-lang/rust-bin" "dev-lang/rust" (nfRust floors),
                "emerge -n app-portage/pycargoebuild"
              ],
            ""
          ]
      | otherwise = []
    sbclRuns
      | isJust (nfSbcl floors) =
          [ runCache
              [ "emerge-webrsync",
                emergeBinThenSrc "dev-lisp/sbcl-bin" "dev-lisp/sbcl" (nfSbcl floors)
              ],
            "",
            "RUN mkdir -p /home/builder \\",
            " && wget -O /tmp/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp \\",
            " && sbcl --non-interactive --no-userinit --no-sysinit \\",
            "      --load /tmp/quicklisp.lisp \\",
            "      --eval '(quicklisp-quickstart:install :path \"/home/builder/quicklisp/\")' \\",
            "      --eval '(ql:quickload :qlot :silent t)' \\",
            "      --quit \\",
            " && rm -f /tmp/quicklisp.lisp \\",
            " && chmod -R a+rX /home/builder/quicklisp",
            ""
          ]
      | otherwise = []
    nodeRuns
      | isJust (nfNode floors) =
          [ runCache
              [ "emerge-webrsync",
                emergeBinThenSrc "net-libs/nodejs-bin" "net-libs/nodejs" (nfNode floors)
              ],
            ""
          ]
      | otherwise = []
    goRuns
      | isJust (nfGo floors) =
          [ runCache
              [ "emerge-webrsync",
                emergeBinThenSrc "dev-lang/go-bin" "dev-lang/go" (nfGo floors)
              ],
            ""
          ]
      | otherwise = []
    bunRuns
      | Just bunVer <- nfBun floors =
          [ runCacheOverlay
              overlay
              [ "emerge-webrsync",
                "mkdir -p /etc/portage/repos.conf /etc/portage/package.accept_keywords",
                "printf '[mndz]\\nlocation = "
                  <> overlay
                  <> "\\nmaster = gentoo\\nauto-sync = no\\n' > /etc/portage/repos.conf/mndz.conf",
                "printf 'dev-lang/bun-bin::mndz ~"
                  <> archTok
                  <> "\\n' > /etc/portage/package.accept_keywords/mndz-bun",
                "emerge -n " <> bunAtom bunVer
              ],
            ""
          ]
      | otherwise = []
    bunAtom ver
      | ver == "0" || T.null ver = "dev-lang/bun-bin::mndz"
      | otherwise = "=dev-lang/bun-bin-" <> ver <> "::mndz"
    builderHome =
      [ "RUN mkdir -p /home/builder/.config /tmp/builder-cache \\",
        " && chmod 0777 /home/builder /home/builder/.config /tmp/builder-cache",
        "",
        "ENV HOME=/home/builder",
        "WORKDIR /home/builder",
        ""
      ]

-- | @-bin@ atom if it exists, else source; binpkg via FEATURES=getbinpkg.
emergeBinThenSrc :: Text -> Text -> Maybe Text -> Text
emergeBinThenSrc binAtom srcAtom mVer =
  "(emerge -n "
    <> spec binAtom
    <> " || emerge -n "
    <> spec srcAtom
    <> ")"
  where
    spec atom = case mVer of
      Just ver
        | ver /= "0",
          not (T.null ver) ->
            "\">=" <> atom <> "-" <> ver <> "\""
      _ -> atom

runCache :: [Text] -> Text
runCache cmds =
  "RUN --mount=type=cache,target=/var/cache/distfiles \\\n\
  \    --mount=type=cache,target=/var/cache/binpkgs \\\n\
  \    "
    <> T.intercalate " \\\n && " cmds

runCacheOverlay :: Text -> [Text] -> Text
runCacheOverlay overlay cmds =
  "RUN --mount=type=bind,from=overlay,source=/,target="
    <> overlay
    <> ",ro \\\n\
       \    --mount=type=cache,target=/var/cache/distfiles \\\n\
       \    --mount=type=cache,target=/var/cache/binpkgs \\\n\
       \    "
    <> T.intercalate " \\\n && " cmds
